// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
                   username,
                   hashed_password,
                   full_name,
                   email
) VALUES (
          $1, $2, $3, $4
         ) RETURNING username, full_name, email, password_changed_at, created_at
`

type CreateUserParams struct {
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
	FullName       string `json:"full_name"`
	Email          string `json:"email"`
}

type CreateUserRow struct {
	Username          string             `json:"username"`
	FullName          string             `json:"full_name"`
	Email             string             `json:"email"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.HashedPassword,
		arg.FullName,
		arg.Email,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE username = $1
`

func (q *Queries) DeleteUser(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, deleteUser, username)
	return err
}

const getUser = `-- name: GetUser :one
SELECT username, full_name, email, password_changed_at, created_at FROM users WHERE username = $1 LIMIT 1
`

type GetUserRow struct {
	Username          string             `json:"username"`
	FullName          string             `json:"full_name"`
	Email             string             `json:"email"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUser(ctx context.Context, username string) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, username)
	var i GetUserRow
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserPassword = `-- name: GetUserPassword :one
SELECT hashed_password FROM users WHERE username = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) GetUserPassword(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRow(ctx, getUserPassword, username)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}

const getUserPrivate = `-- name: GetUserPrivate :one
SELECT u.username, u.hashed_password, u.full_name, u.email, u.password_changed_at, u.created_at, COALESCE(a.level_right, 0) as level_right
    FROM users as u
    LEFT JOIN admins as a on a.owner = u.username
    WHERE u.username = $1
    LIMIT 1
`

type GetUserPrivateRow struct {
	Username          string             `json:"username"`
	HashedPassword    string             `json:"hashed_password"`
	FullName          string             `json:"full_name"`
	Email             string             `json:"email"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	LevelRight        pgtype.Numeric     `json:"level_right"`
}

func (q *Queries) GetUserPrivate(ctx context.Context, username string) (GetUserPrivateRow, error) {
	row := q.db.QueryRow(ctx, getUserPrivate, username)
	var i GetUserPrivateRow
	err := row.Scan(
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.LevelRight,
	)
	return i, err
}

const isAdmin = `-- name: IsAdmin :one
SELECT bool(coalesce(a.level_right, 0)) FROM users as u LEFT JOIN admins as a on a.owner = u.username WHERE u.username = $1 LIMIT 1
`

func (q *Queries) IsAdmin(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, isAdmin, username)
	var bool bool
	err := row.Scan(&bool)
	return bool, err
}

const updateName = `-- name: UpdateName :one
UPDATE users SET full_name = $2 WHERE username= $1 RETURNING username, full_name, email, password_changed_at, created_at
`

type UpdateNameParams struct {
	Username string `json:"username"`
	FullName string `json:"full_name"`
}

type UpdateNameRow struct {
	Username          string             `json:"username"`
	FullName          string             `json:"full_name"`
	Email             string             `json:"email"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateName(ctx context.Context, arg UpdateNameParams) (UpdateNameRow, error) {
	row := q.db.QueryRow(ctx, updateName, arg.Username, arg.FullName)
	var i UpdateNameRow
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE users SET password_changed_at = NOW(), hashed_password = $2 WHERE username = $1 RETURNING username, full_name, email, password_changed_at, created_at
`

type UpdatePasswordParams struct {
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
}

type UpdatePasswordRow struct {
	Username          string             `json:"username"`
	FullName          string             `json:"full_name"`
	Email             string             `json:"email"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (UpdatePasswordRow, error) {
	row := q.db.QueryRow(ctx, updatePassword, arg.Username, arg.HashedPassword)
	var i UpdatePasswordRow
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}
